Correction defects
Go0osee/RetrofitJsonNews pull request #1
Opened 2022-03-26 19:01 UTC by Go0osee

2022-03-26 19:22 UTC, Vinny94051 requested changes

2022-03-26 19:22 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/domain/ext/Ext.kt
> +package com.example.retrofitjsonnews.domain.ext
Почему этот метод лежит в домене, когда это экстеншн к view, а view это presentation слой?

2022-03-26 19:22 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/domain/ext/Mapper.kt
> +            item.previewUrl != null ->
форматирование не читабельное, тут вроде и условие и ветка влазит в одну строку т.е. 
`index == 0 -> items.add(Date(item.publishedAt.toDate()))` 
и вот тебе котлин конвеншн на when
![image](https://user-images.githubusercontent.com/37775244/160253861-51e3dd84-033c-4b65-b07e-7c0027848574.png)

2022-03-26 19:22 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/domain/ext/Mapper.kt
> +fun String.toDate(): String =
Если хочешь оформить это как экстеншн, то лучше вынести в отдельный файл + передавать в параметр формат по которому парсишь

2022-03-26 19:22 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/domain/ext/Mapper.kt
> +                .parse(this.substring(0, 10)))
это не нужно, тебе просто изначально нужно передавать формат даты которая с бека приходит, он вроде epoch называется 
проще всего гуглить epoch to Date

2022-03-26 19:22 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/data/model/NewsResponse.kt
> +    val articleUrl: String,
тут зря нал убрал, никогда не знаешь, что бэк отправить

2022-03-26 19:22 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/presentation/MainActivity.kt
> +                    loudRecycler()
load ты имел в виду наверн)

2022-03-26 19:22 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/presentation/MainActivity.kt
>          searchEditText.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
в эстеншн тут не вынес

2022-03-26 19:22 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/presentation/MainActivity.kt
> +            numberOfResult.text = getString(R.string.countOfNews) + items.count
в строки можно передавать параметры, 
`<string name:....> Количество результатов %s </string>`
потом 
`getString(R.string..., значение)`

2022-03-26 19:22 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/presentation/MainActivity.kt
> +    private fun search(searchWord: String) {
ну вроде как не обязательно это в метод выносить

2022-03-26 19:30 UTC, Go0osee commented on app/src/main/java/com/example/retrofitjsonnews/domain/ext/Mapper.kt
> +            item.previewUrl != null ->
не понял ни слова

2022-03-26 19:30 UTC, Go0osee commented on app/src/main/java/com/example/retrofitjsonnews/domain/ext/Mapper.kt
> +fun String.toDate(): String =
понял только что могу вынести в отдельный файл

2022-03-26 19:31 UTC, Go0osee commented on app/src/main/java/com/example/retrofitjsonnews/domain/ext/Mapper.kt
> +                .parse(this.substring(0, 10)))
ничего не понял

2022-03-26 19:31 UTC, Go0osee commented on app/src/main/java/com/example/retrofitjsonnews/data/model/NewsResponse.kt
> +    val articleUrl: String,
Ага, я то уберу, но потом в модельке надо будет поля делать nullable, и ты опять напишешь что я редиска

2022-03-26 19:32 UTC, Go0osee commented on app/src/main/java/com/example/retrofitjsonnews/presentation/MainActivity.kt
>          searchEditText.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
я не смог, не понимаю как

2022-03-26 19:40 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/domain/ext/Mapper.kt
> +                .parse(this.substring(0, 10)))
зачем ты используешь метод substring, оно и без него работать должно

2022-03-26 19:41 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/data/model/NewsResponse.kt
> +    val articleUrl: String,
зачем их делать налабл? если эти поля null, то их вообще в список для отображения добавлять не надо

2022-03-26 19:45 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/presentation/MainActivity.kt
>          searchEditText.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
думай дальше, я тебе даже сигнатуру накидал
 `fun SearchView.setOnQueryTextSubmitListener(action : (String?) -> Boolean) { … }`

2022-03-26 19:45 UTC, Go0osee commented on app/src/main/java/com/example/retrofitjsonnews/data/model/NewsResponse.kt
> +    val articleUrl: String,
мне в маппере делать еще проверку на null ?

2022-03-26 19:56 UTC, Vinny94051 commented on app/src/main/java/com/example/retrofitjsonnews/data/model/NewsResponse.kt
> +    val articleUrl: String,
да

2022-03-27 09:34 UTC, Vinny94051 approved these changes

2022-03-28 15:55 UTC, merged